name: deploy-these-guns

on: [workflow_dispatch]

env:
    AZURE_RESOURCEGROUP_NAME: rg-testing-sp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          path: main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS_CLI }}
      - uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./bicep/main.bicep